name = "servaster-worker"
main = "worker/index.ts"
compatibility_date = "2024-12-01"

# Custom domain
routes = [
  { pattern = "config.sgoip.com/*", zone_name = "sgoip.com" }
]

[[kv_namespaces]]
binding = "DIALPLAN_KV"
id = "3c6e5d08ab7e470182bcd63c87aae82a"
